### PR TITLE
Create Login Page

### LINKED ISSUE #19: Login page wireframe
**Task**

Design a high fidelity login page for users
Tools used : Figma , Adobe XD 

**Implementation**

Create designs and share screenshots in comment section 
Create a folder in Resource section (Name- Wireframes)
Make pr to Resource branch 

**Procedure**

Claim this issue: Comment below that you want to work on this issue 
Write relevant commit message 
Create a PR

### PR DESCRIPTION
**Pull request by kichloo**
Closes #19

### CODE REVIEW

**Comment by kichloo** [comment]
@Swarnimashukla Pl check this

website_blocker

**Comment by kichloo** [comment]
Design 2

website_blocker

**Comment by kichloo** [comment]
Design 2

website_blocker

**Comment by Swarnimashukla** [comment]
@kichloo  what does menu1 and menu2 inside login form represent ? what is your thought process?

**Comment by kichloo** [comment]
Menu 1: Login with Google
Menu 2: Login with Facebook

In the footer, 
Menu 1 can be T&C
Menu 2 can be Privacy policy

**Comment by Swarnimashukla** [comment]
> Menu 1: Login with Google
> Menu 2: Login with Facebook
> 
> In the footer,
> Menu 1 can be T&C
> Menu 2 can be Privacy policy

Nice 
Do write these things in place of menu and also add icons of facebook and google where you have marked circle.
Make these changes and make pr as discussed. Add images inside resource folder and then commit .

**Comment by kichloo** [comment]
@Swarnimashukla Done the required changes

website_blocker

**Pull request closed without merging**
