### PR TITLE
Create T&C

### LINKED ISSUE #41: Terms and Conditions wireframe page
The wireframe for the T&C page.

### PR DESCRIPTION
**Pull request by kichloo**
Closes #41

### CODE REVIEW

**Comment by kichloo** [comment]
body

**Comment by kichloo** [comment]
Pl check the above wireframe.

**Review by Swarnimashukla — CHANGES_REQUESTED** [review]
@kichloo  check for latest front page design by aakansha and change your header and footer accordingly , replace menu1 , menu2 with names given by aakansha .

Also include terms and conditions instead of text here to make it a high fidelity wireframe . It should be detailed enough so that person who codes don't have to check what to include inside the page , because that's a designer's job to provide complete layout .

**Comment by kichloo** [comment]
@Swarnimashukla Can you provide any reference to akansha's work (the PR number)?

**Comment by Swarnimashukla** [comment]
> @Swarnimashukla Can you provide any reference to akansha's work (the PR number)?

 #44  @kichloo

**Comment by kichloo** [comment]
t c

**Review by Swarnimashukla — APPROVED** [review]
Good job 👍

**Pull request merged**
