### PR TITLE
Added NavBar

### PR DESCRIPTION
**Pull request by kmrakash**
#21

### CODE REVIEW

**Review by Swarnimashukla — CHANGES_REQUESTED** [review]
Share image of result achieved after this code is implemented in comment section.
Remove extra spaces use [prettier](https://prettier.io/) 
Add a new line at the end of code

**Comment by kmrakash** [comment]
I have added a bootstrap theme nav bar , since i don't have any design.

**Comment by imsahil007** [comment]
> I have added a bootstrap theme nav bar , since i don't have any design.

Just add a screenshot so that I can accept the changes and merge it

**Review by imsahil007 — CHANGES_REQUESTED** [review]
Add screenshots while updating the front end

**Comment by kmrakash** [comment]
Mobile ViewPort
image

Desktop ViewPort
image

**Pull request merged**
