### PR TITLE
Create Wireframes

### LINKED ISSUE #18: Landing page wireframe
**Task**

Create a high fidelity mockup for front page of website .
Tools used : Can be Figma , Adobe XD 

**Implementation**
Create designs and share screenshots in comment section .
Create a folder in Resource section (Name- Wireframes)
Make pr to Resource branch folder.

**Procedure**
Claim this issue: Comment below that you want to work on this issue .
Write relevant commit message .
Create a PR .

### PR DESCRIPTION
**Pull request by kichloo**
Closes #18

### CODE REVIEW

**Comment by kichloo** [comment]
website_blocker - Copy

**Comment by kichloo** [comment]
There is a `Download` button, the `Login` button for users and a `Sign-Up` button for new users, which can be linked to Google, Facebook. 
The `Chrome Extension` will be a clickable button, which will add the extension directly.
The `Available on` lists the platforms on which the extension will work.

**Review by Swarnimashukla — CHANGES_REQUESTED** [review]
Good job , here are few changes I would suggest before merging this pr .

1. Reduce size of button at header and header section 
2. Check for color contrast in blue buttons(reduce opacity  or change text color to make it visible)
3. Merge login /signup button
4. Add About us button , services button , product demo button
5. Add a professional footer to website

**Comment by kichloo** [comment]
@Swarnimashukla Did all the required changes.

**Comment by kichloo** [comment]
@Swarnimashukla  Done the required changes

website_blocker

**Review by Swarnimashukla — CHANGES_REQUESTED** [review]
Look for these wireframe designs for footer and other part of website

[Design1](https://www.behance.net/gallery/97825917/Free-Company-Website-Wireframe-Adobe-XD?tracking_source=search_projects_recommended%7Cwebsite%20wireframe)

[Design2](https://www.behance.net/gallery/29345451/WebWire-Web-Wireframe-UI-Stater-Kit?tracking_source=search_projects_recommended%7Cwebsite%20wireframe)

1. Try to include slider images at the top rather than single image 
2. Add more sections in body like features section
3. Customer testimonial section 

Generate PR request to resources branch as mentioned in issue rather than master branch

**Comment by kichloo** [comment]
Can you please elaborate on the part of the slider section.
Also, where to add more sections as it has already clogged up a bit and adding more sections seems difficult. 
Also, the generally the About, Demo links can be added on the footer section, but haven't added up because it is already on the header section.

**Comment by Swarnimashukla** [comment]
> Can you please elaborate on the part of the slider section.
> Also, where to add more sections as it has already clogged up a bit and adding more sections seems difficult.
> Also, the generally the About, Demo links can be added on the footer section, but haven't added up because it is already on the header section.


You have added an image instead of one single image  show slider with three dots at the bottom and arrows in sides (like real sliding images look on website .

Divide page into two separate wireframes 
1. header + first half page 
2. second half of page + footer 

For footer check the links I have provided 
1. Add copyright  , terms and conditions etc. in footer 

check this : https://www.behance.net/gallery/93994965/Water-Monitoring-System

**Comment by kichloo** [comment]
website_blocker

**Comment by kichloo** [comment]
website_blocker

**Review by Swarnimashukla — APPROVED** [review]

**Pull request merged**
